"""Added new columns to Regulator table

Revision ID: ba4a6db574c8
Revises: 4e74f94ad765
Create Date: 2022-01-31 09:52:23.871228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba4a6db574c8'
down_revision = '4e74f94ad765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regulator', sa.Column('organism', sa.String(length=128), nullable=True))
    op.add_column('regulator', sa.Column('start', sa.Integer(), nullable=True))
    op.add_column('regulator', sa.Column('stop', sa.Integer(), nullable=True))
    op.add_column('regulator', sa.Column('strand', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regulator', 'strand')
    op.drop_column('regulator', 'stop')
    op.drop_column('regulator', 'start')
    op.drop_column('regulator', 'organism')
    # ### end Alembic commands ###
